
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.evilcraft]
		enable_compat_evilcraft = true

	[Compatibility.mca]
		enable_compat_mca = true

	[Compatibility.ctov]
		enable_compat_ctov = true

